namespace: shopnow-app

frontend:
  image: samdonalda/shopnow-frontend
  tag: latest
  replicas: 1
  servicePort: 80

backend:
  image: samdonalda/shopnow-backend
  tag: latest
  replicas: 1
  port: 5000
  mongoUri: mongodb://mongo-service:27017/shopnow

mongo:
  image: mongo
  tag: "6.0"
  storage: 5Gi
  port: 27017

ingress:
  enabled: true
  pathPrefix: /aryan
